### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by nyxaria** [GummiArmCE/fusion360_scripts#1]
Hi, I was wondering, is this project is usable as-is to export a fusion360 file into urdf? Or do you still need to save it to a step file, modify occurrences and then use the solidworks plugin?

Thanks :)

**Comment by frederico-klein** [comment]
Hi. This project is meant to replace the need of solidworks entirely. 

I've just successfully created the first complete model of our arms using it (8 dof, all axial joints harvester-arm), so it is already functional, however it is still lacking when considering the amount of control the solidworks plugin offers. 

Some features are missing, such as prismatic joints or the possibility to edit the end-stage generated urdf joint by joint and link by link. 

I'd have to say it is still in early-alpha testing, but it is already much faster to use than exporting as a step file and redefining every joint (with origin and rotation axis) in solidworks.

Please do try it out and tell me what you think!
